---
- name: Molecule.default.verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Molecule.default.verify | Include vars of vars/main.yml
      ansible.builtin.include_vars:
        file: ../../vars/main.yml

    - name: Molecule.default.verify | Include all tests
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - ../tests/variables/main.yml
        - ../tests/etcd/*.yml
        - ../tests/patroni/*.yml
        - ../tests/postgres/*.yml
        - ../tests/roles/confd/main.yml
        - ../tests/roles/deploy-finish/main.yml
        - ../tests/roles/haproxy/main.yml
        - ../tests/roles/patroni/main.yml
        - ../tests/roles/pre-checks/main.yml
        - ../tests/roles/swap/main.yml
